logging:
    file:
        name: /logs/lotteOn.log

    level:
        jdbc:
            resultsettable: info
            sqlonly: info
            sqltiming: info
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
                sql: info
        root: info
        org.springframework.web: info
server:
    port: 8085
    servlet:
        context-path: /

spring:
    devtools:
        restart:
            enabled: false
    profiles:
        active: prod
        include: local
    application:
        name: LotteOnProject-3조
        version: ${version}

    mail:
        host: smtp.gmail.com
        port: 587
        username: woo24465@gmail.com
        password: mawj nxfq tiwx regc
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true

    security:
        remember-me:
            key: "1234Asd@"

        oauth2:
            client:
                registration:
                    google:
                        client-id: 260686576423-cd9o4qepuuq5mfnprhbftso2h3h8nqv5.apps.googleusercontent.com
                        client-secret: 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
                        redirect-uri: http://localhost:8085/login/oauth2/code/google
                        scope:
                            - email
                            - profile

                    kakao:
                        client-id: e854d74518514c68abdc06c8cd750f0f
                        client-secret: 0PlxjR5lcZSTbH5aXvrJhaT53s91vaBI
                        scope:
                            - profile_nickname
                            - account_email
                        redirect-uri: http://localhost:8085/login/oauth2/code/kakao
                        authorization-grant-type: authorization_code
                        client-authentication-method: client_secret_post
                        client-name: Kakao

                    naver:
                        client-id: hzcfmimrVKAxW_vhgGlX
                        client-secret: amsujfvscS
                        scope:
                            - name
                            - email
                        redirect-uri: http://localhost:8085/login/oauth2/code/naver
                        authorization-grant-type: authorization_code
                        client-name: Naver

                provider:
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/auth
                        token-uri: https://oauth2.googleapis.com/token
                        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                        user-name-attribute: name

                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id

                    naver:
                        authorization_uri: https://nid.naver.com/oauth2.0/authorize
                        token_uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user_name_attribute: response